FROM python:3.8.6-buster

RUN mkdir /great_expectations
WORKDIR /great_expectations
ADD . /great_expectations/

RUN apt-get update -yqq \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && apt-get install -y --no-install-recommends gawk \
    && apt-get install -y --no-install-recommends grep \   
    && apt-get install --no-install-recommends -yqq ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "bash", "/great_expectations/scripts/entrypoint.sh" ]