version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_PULSE_SECRET: /app/pulse-secret
      APP_DB_SECRET: /app/db-secret
      APP_DW_SECRET: /app/dw-secret
      APP_SMTP_SECRET: /app/smtp-secret
    volumes:
      - ~/Projects/data-quality/time-series-data-quality/:/app/folder/
      - ~/Projects/secrets/blocket-secret:/app/db-secret
      - ~/Projects/secrets/db-secret:/app/dw-secret
      - ~/Projects/secrets/pulse-secret:/app/pulse-secret
      - ~/Projects/secrets/smtp-secret:/app/smtp-secret
