- defaultTab: nodes
  description: |-
        path: Data-Quality/ge-data-quality
        sudo docker run --rm --net=host \
                    -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                    -v /home/bnbiuser/secrets/aws_greatexp:/app/aws-secret \
                    -e APP_DB_SECRET=/app/db-secret \
                    -e APP_AWS_SECRET=/app/aws-secret \
                    containers.mpi-internal.com/yapo/data-quality-ge-data-quality:latest
  executionEnabled: true
  group: DATA-QUALITY
  loglevel: DEBUG
  name: Data - Great Expectation verifications
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
      plugin:
        configuration:
          slack_channel: ''
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T017F9KHA1Y/B01BL7C1CSY/Ai9NzdCrBUA5Ru5sa8JHYrjR
        type: SlackNotification
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '03'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/data-quality-ge-data-quality:latest
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/aws_greatexp:/app/aws-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        -e APP_AWS_SECRET=/app/aws-secret \
                        containers.mpi-internal.com/yapo/data-quality-ge-data-quality:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
