FROM python:3.7.2-slim

COPY . /app
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && apt-get install -y --no-install-recommends gawk \
    && apt-get install -y --no-install-recommends grep \
    && rm -rf /var/lib/apt/lists/* \ 
    && pip install -r requirements.txt \
    && apt-get purge -y --auto-remove gcc build-essential \
    && apt-get install -y ca-certificates

#ENTRYPOINT [ "bash", "/app/scripts/entrypoint.sh" ]
CMD [ "bash" ]