version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      DATA_WATCH_CONF: /app/datawatch.ini
    volumes:
      - /keys/datawatch.ini:/app/datawatch.ini